### PR TITLE
Reorganization of examples

### PR DESCRIPTION
**Pull request by dangunter**
As per discussion during the IDAES tech team meeting in January 2023, this PR will reorganize the repository to reflect the status of different notebooks.

### CODE REVIEW

**Comment by dangunter** [comment]
image

**Comment by dangunter** [comment]
Current status: test failures:
```
FAILED idaes_examples/notebooks/docs/custom/unit_models/custom_compressor_test.ipynb::
FAILED idaes_examples/notebooks/docs/custom/unit_models/custom_heater_test.ipynb::
FAILED idaes_examples/notebooks/docs/flowsheets/hda_flowsheet_with_costing_test.ipynb::
FAILED idaes_examples/notebooks/docs/surrogates/best_practices_optimization_test.ipynb::
FAILED idaes_examples/notebooks/docs/flowsheets/hda_flowsheet_with_distillation_test.ipynb::
FAILED idaes_examples/notebooks/docs/flowsheets/methanol_synthesis_test.ipynb::
FAILED idaes_examples/notebooks/docs/surrogates/alamo/alamo_flowsheet_optimization_test.ipynb::
FAILED idaes_examples/notebooks/docs/surrogates/pysmo/pysmo_flowsheet_optimization_test.ipynb::
FAILED idaes_examples/notebooks/docs/tut/hda_flowsheet_test.ipynb::
FAILED idaes_examples/notebooks/docs/tut/visualizer_tutorial_test.ipynb::
FAILED idaes_examples/notebooks/docs/unit_models/operations/heat_exchanger_0d_test.ipynb::
FAILED idaes_examples/notebooks/docs/unit_models/operations/pump_test.ipynb::
FAILED idaes_examples/notebooks/docs/unit_models/operations/turbine_test.ipynb::
FAILED idaes_examples/notebooks/docs/unit_models/operations/compressor_test.ipynb::
FAILED idaes_examples/notebooks/internal/active/power_gen/ngcc/ngcc_soec_test.ipynb::
FAILED idaes_examples/notebooks/internal/active/power_gen/ngcc/ngcc_test.ipynb::
FAILED idaes_examples/notebooks/docs/surrogates/omlt/keras_flowsheet_optimization_test.ipynb::
```

**Comment by dangunter** [comment]
After a lot of messing around, I have the notebook errors down to a set that are not obviously due to the reorganization. I will need help fixing these, but it may be best to merge what I have so we can all work off the same codebase.

For the record, here's what's left and who I think can help move them forward.

@eslickj I will need your help with the `ngcc_soec` example, which is failing in the nl_writer:
```
~\miniconda3\envs\idaes3\lib\site-packages\pyomo\repn\plugins\nl_writer.py in _write_nl_expression(self, repn, include_const)
   1497                     self.template.const % repn.const)
   1498             self.ostream.write(
-> 1499                 nl % tuple(map(self.var_id_to_nl.__getitem__, args))
   1500             )
   1501         elif include_const:

TypeError: not enough arguments for format string
```

@andrewlee94 I will need your help identifying who to ask about some asserts not passing in the unit models:
* compressor_test.ipynb
```
AssertionError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_12720\3316535041.py in <cell line: 5>()
      3 # Check results
      4 assert m.fs.compr_case_1.outlet.pressure[0].value == pytest.approx(34620700.0, abs=1e-2)
----> 5 assert m.fs.compr_case_1.work_isentropic[0].value == pytest.approx(
      6     135439976.18, abs=1e-2
      7 )
```
* turbine_test.ipynb:
```
AssertionError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_15056\1636448963.py in <cell line: 5>()
      3 # Check results
      4 assert m.fs.turbine_case_1.outlet.pressure[0].value == pytest.approx(140000, abs=1e-2)
----> 5 assert m.fs.turbine_case_1.work_mechanical[0].value == pytest.approx(
      6     -19597.158, abs=1e-2
      7 )
```
And also @andrewlee94 or literally anybody, I will need help with assigning someone to this error in omlt:
```
~\miniconda3\envs\idaes3\lib\site-packages\idaes\core\surrogate\keras_surrogate.py in <module>
     27
     28 if omlt_available:
---> 29     from omlt import OmltBlock, OffsetScaling
     30     from omlt.neuralnet import (
     31         FullSpaceContinuousFormulation,

ImportError: cannot import name 'OmltBlock' from 'omlt' (C:\Users\dang\src\idaes\dangunter\idaes-examples\idaes_examples\notebooks\docs\surrogates\omlt\__init__.py)
```

**Comment by andrewlee94** [comment]
@dangunter For the assertion failures, are you using the latest versions of the examples from `examples-pse`, and are you using the latest `main` branch of Pyomo? We had to fix a lot of little things like this in the transition to the new Pyomo solver writer, so we should make sure you are running with the latest versions of both.

For the OMLT failure - which version of OMLT are you using? We are currently stuck using an older version of OMLT (although the DISPATCHES team just opened a PR to fix that).

**Comment by eslickj** [comment]
@jsiirola and @andrewlee94, here's some junk I pulled out of the nl_writer fail

```
in _write_nl_expression
nl = 
o2
n0.001
o2
n-13.209932196966305
o5
o2
n9.328531204477933e-07
v%s
n0

repn = AMPLRepn(mult=1, const=0.0, linear={6085815296: 0.001}, nonlinear=('o2\nn0.001\no2\nn-13.209932196966305\no5\no2\nn9.328531204477933e-07\nv%s\nn0\n', []), nl=None, named_exprs={6264423296})

args = []

repn.nolinear = ('o2\nn0.001\no2\nn-13.209932196966305\no5\no2\nn9.328531204477933e-07\nv%s\nn0\n', [])

at line 1203:
info[0] = fs.b1.costing.bare_erected_cost_eq['8.4']
info[0].body = (fs.b1.costing.bare_erected_cost['8.4'] - 0.001*(MUSD_2018/kUSD_2018)*(fs.b1.costing.ref_cost['8.4']*kUSD_2018)*((7936.641438655591*(lb*s/h/kg)*(fs.ngcc.hrsg.prop_gas.mw_comp[N2]*fs.ngcc.hrsg.econ_hp1.hot_side.properties_in[0.0].flow_mol_comp[N2] + fs.ngcc.hrsg.prop_gas.mw_comp[O2]*fs.ngcc.hrsg.econ_hp1.hot_side.properties_in[0.0].flow_mol_comp[O2] + fs.ngcc.hrsg.prop_gas.mw_comp[CO2]*fs.ngcc.hrsg.econ_hp1.hot_side.properties_in[0.0].flow_mol_comp[CO2] + fs.ngcc.hrsg.prop_gas.mw_comp[H2O]*fs.ngcc.hrsg.econ_hp1.hot_side.properties_in[0.0].flow_mol_comp[H2O]))/(fs.b1.costing.ref_param['8.4']*(lb/h)))**fs.b1.costing.exp['8.4'])*0.001
```

I'm not sure what is happening but repn wants a variable but the list of variables is empty.  I'll keep looking into it, but if anyone has any idea, it could help me out.  I'm not really familiar with the inner workings of the costing.

**Comment by dangunter** [comment]
@eslickj the bugfix in Pyomo helped with the NGCC SOEC notebook. Thanks for looking into this quickly. 
But now there is an assertion error when checking the results.
Near the bottom of the *Create and Initialize the NGCC + SOEC Model* section, there is a testing cell:
```
print(total_fixed)
print(ac)

# Check anualized fixed O&M costs
assert total_fixed == pytest.approx(74.690994, rel=1e-3)

# Check anualized TASC
assert ac == pytest.approx(150.09339, rel=1e-3)
```
This fails, printing these values:
```
74.87796601116479
150.5208387129365
```
Any ideas what is wrong?

**Comment by dangunter** [comment]
After some discussion, we decided to *temporarily* increase the tolerance for the SOEC notebook tests (1e-2 vs. 1e-3). It now passes! This was the last failing notebook, so moving this out of Draft.

**Pull request merged**
