### PR TITLE
Pandas deprecation for series call

### LINKED ISSUE #108: pandas deprecation warnings in parameters estimation notebooks
image

https://github.com/search?q=repo%3AIDAES%2Fexamples+%22Series+is+deprecated%22&type=code

### PR DESCRIPTION
**Pull request by agarciadiego**
# Removes FutureWarning deprecation message on parmest notebooks on how the elements of the dataframe/dictionary are indexed

# Fixes #108 

Changes the way of calling the data and differentiates between a dictionary and a dataframe. Based on parmest examples in Pyomo repo
----
Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

    I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
    I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

----
📚 Documentation preview 📚: https://idaes-examples--110.org.readthedocs.build/en/110/

### CODE REVIEW

**Comment by bpaul4** [comment]
Hi @agarciadiego, the number of lines changed seem to be inflated because of the regenerated notebook output. Could you please elaborate on what specific sections are updated in the PR?

There also seem to be some file conflicts.

**Comment by lbianchi-lbl** [comment]
> Hi @agarciadiego, the number of lines changed seem to be inflated because of the regenerated notebook output. Could you please elaborate on what specific sections are updated in the PR?
> 
> There also seem to be some file conflicts.

@bpaul4 thanks for bringing this up. I'm working with @agarciadiego to understand why these conflicts are showing up. I've already (unsuccessfully) tried to solve the conflicts locally, so it's likely that I'll open a new PR.

**Comment by andrewlee94** [comment]
@agarciadiego What is the status of this PR? Is it something for the May release?

**Comment by agarciadiego** [comment]
> @agarciadiego What is the status of this PR? Is it something for the May release?

I'll try to get it merged early next week

**Comment by agarciadiego** [comment]
Replaced by #117

**Pull request closed without merging**
