### PR TITLE
Moving held OMLT notebook

### LINKED ISSUE #27: idaesx gui command fails due to input file encoding
```
❯ idaesx gui
-> Load notebooks into GUI
Traceback (most recent call last):
  File "C:\Users\dkgun\miniconda3\envs\idaes_py310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\dkgun\miniconda3\envs\idaes_py310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\dkgun\miniconda3\envs\idaes_py310\Scripts\idaesx.exe\__main__.py", line 7, in <module>
  File "C:\Users\dkgun\src\dangunter\idaes-examples\idaes_examples\build.py", line 585, in main
    sys.exit(func(args))
  File "C:\Users\dkgun\src\dangunter\idaes-examples\idaes_examples\build.py", line 442, in gui
    nb = browse.Notebooks()
  File "C:\Users\dkgun\src\dangunter\idaes-examples\idaes_examples\browse.py", line 117, in __init__
    find_notebooks(self._root, self._toc, self._add_notebook)
  File "C:\Users\dkgun\src\dangunter\idaes-examples\idaes_examples\util.py", line 128, in find_notebooks
    callback(path, **kwargs)
  File "C:\Users\dkgun\src\dangunter\idaes-examples\idaes_examples\browse.py", line 131, in _add_notebook
    self._nb[key] = Notebook(name, section, tpath, nbtype=ext)
  File "C:\Users\dkgun\src\dangunter\idaes-examples\idaes_examples\browse.py", line 217, in __init__
    self._get_description()
  File "C:\Users\dkgun\src\dangunter\idaes-examples\idaes_examples\browse.py", line 256, in _get_description
    data = json.load(f)
  File "C:\Users\dkgun\miniconda3\envs\idaes_py310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\dkgun\miniconda3\envs\idaes_py310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1604: character maps to <undefined>
NativeCommandExitException: Program "idaesx.exe" ended with non-zero exit code: 1.
```

### PR DESCRIPTION
**Pull request by agarciadiego**
# Moving held OMLT notebook

Fixes #27

Moved OMLT files and deleted empty `__init__.py` file which was causing import error in tests

----
Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

    I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
    I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

----
:books: Documentation preview :books:: https://idaes-examples--35.org.readthedocs.build/en/35/

### CODE REVIEW

**Comment by andrewlee94** [comment]
@agarciadiego @dangunter I am not seeing this example in the docs built during the tests - is there something missing to add the notebook into the docs?

**Comment by agarciadiego** [comment]
@andrewlee94 Missed the content table. Should be included now

**Review by dangunter — COMMENTED** [review]
All the Python dependencies are now under the 'mod' (for 'modules') subdirectory. You will see there is already an AR_training_methods.py under mod/surrogates that you can import into the omlt code, and you can remove the one in the docs tree.

**Review by dangunter — COMMENTED** [review]
I think you should change the title of the OMLT section, i.e. the header of docs/surrogate/omlt/index.md, to the name of the package, i.e.:
# OMLT: Optimization and Machine Learning Toolkit

**Review by andrewlee94 — CHANGES_REQUESTED** [review]
This is looking good. I did find at least one typo however:

Section 3.2: Sequnetial -> sequential
Section 3.3: "surrogates are fit the data" grammar is wrong.

**Review by andrewlee94 — APPROVED** [review]

**Pull request merged**
