### PR TITLE
Migrating New Unit Model Examples

### PR DESCRIPTION
**Pull request by MarcusHolly**
Migrates unit model examples that I made across 4 PRs in the old examples-pse repo.

### CODE REVIEW

**Comment by MarcusHolly** [comment]
I think everything is included now, but let me know if I missed anything.

**Comment by lbianchi-lbl** [comment]
We can use this PR as a test as soon as we have an initial implementation of the CI infrastructure.

**Comment by dangunter** [comment]
All the files are moving in #10 so I guess I'll need to move them in the right place. @MarcusHolly  are these expected to be in the external-facing documentation?

**Comment by MarcusHolly** [comment]
> All the files are moving in #10 so I guess I'll need to move them in the right place. @MarcusHolly are these expected to be in the external-facing documentation?

@dangunter I'm not sure exactly what you mean by "external-facing", but if are just asking if they fall under "custom>unit models" (notation from the screenshot in your PR), then the answer is yes.

**Comment by dangunter** [comment]
@MarcusHolly If these aren't any different than the examples in the examples-pse repo, then I think I will probably just move them from there, in which case we could close this PR without merging once I've done that

**Comment by MarcusHolly** [comment]
> @MarcusHolly If these aren't any different than the examples in the examples-pse repo, then I think I will probably just move them from there, in which case we could close this PR without merging once I've done that

I see. Yes, these are the examples from the examples-pse repo, so feel free to close this PR.

**Comment by dangunter** [comment]
Closing now that it is a duplicate of work going on in the 'examples' repo

**Pull request closed without merging**
